import type { Question } from "@/components/QuestionPanel";
import { topic01DefaultCode } from "./topic-01-raw-response";
import { topic02DefaultCode } from "./topic-02-system-prompt";
import { topic03DefaultCode, topic03FixedCode } from "./topic-03-state";
import { topic04DefaultCode, topic04ToolCode } from "./topic-04-tools";
import { topic05DefaultCode, topic05SchemaCode } from "./topic-05-structured-output";
import { topic06DefaultCode } from "./topic-06-multimodal";
import { topic07DefaultCode, topic07RagCode } from "./topic-07-rag";
import { topic08DefaultCode } from "./topic-08-reasoning";
import { topic09DefaultCode } from "./topic-09-streaming";
import { topic10DefaultCode } from "./topic-10-mcp";
import { topic11DefaultCode, topic11FixedCode } from "./topic-11-context-window";
import { topic12DefaultCode } from "./topic-12-image-generation";
import { topic13DefaultCode, topic13EvalCode } from "./topic-13-evals";
import { topic14DefaultCode } from "./topic-14-agents";
import { topic15DefaultCode } from "./topic-15-multi-agent";
import { topic16DefaultCode } from "./topic-16-skills";
import { topic17DefaultCode, topic17CodeInterpreterCode } from "./topic-17-code-interpreter";

export type Topic = {
  id: string;
  title: string;
  description: string; // markdown shown above the editor
  defaultCode?: string; // pre-filled editable TS; omit for a text-only topic (e.g. the intro)
  question?: Question; // optional interactive checkpoint question
  followUp?: {
    title: string; // heading shown on the follow-up step card
    intro: string; // markdown shown above the second (fixed) code block
    code: string; // a second editable/runnable code block, after the checkpoint
    explanation: string; // takeaway markdown revealed after running the fixed code
  };
};

/**
 * Topic definitions, keyed by `id`. Defined in creation order; the displayed
 * order and the numbers in each `title` come from `TOPIC_ORDER` below. To
 * reorder the workshop, edit `TOPIC_ORDER` (and the title numbers) — you don't
 * need to move entries here.
 *
 * A topic without `defaultCode` is shown as a text-only page (no editor) — used
 * for the course introduction.
 */
const topicDefinitions: Topic[] = [
  {
    id: "introduction",
    title: "Introduction",
    description: [
      "## 👋 Welcome to the Generative AI interactive workshop",
      "",
      "You've all seen the power of ChatGPT, Claude, or Microsoft Copilot: seemingly all-knowing AI",
      "that connects to everything, answers anything, and works across text, images, and speech.",
      "",
      "Yet underneath, each is **merely a model** — a **Large Language Model (LLM)** for text, or an",
      "image, speech, or video model — and on its own that foundation has limited, frozen knowledge,",
      "can't connect to anything, and can't even count reliably. So how do we get from that to the",
      "assistants you know? **That's exactly what this workshop unpacks.**",
      "",
      "Over the next few topics you'll get hands-on with an LLM and build an intuition for how it",
      "actually behaves — and how each capability is added on top, piece by piece.",
      "",
      "## 🎯 Who this is for",
      "",
      "This course is aimed at **developers** — the examples are real code and lean toward how you'd",
      "build with these models. But **you don't need to know how to program to follow along**. Every",
      "snippet is small, explained in plain language, and ready to run — you can read it, press **Run**,",
      "and learn from what comes back even if you've never written code before.",
      "",
      "## ⚙️ How this works",
      "",
      "- **The LLM is already hosted for you.** It runs on a server we've set up, so there's",
      "nothing to install or configure — you can start experimenting right away.",
      "- **You learn by running code.** Each topic gives you a small, real code snippet that",
      "calls the model. Press **Run** and watch what comes back.",
      "- **Expect to change the code.** Experiments often only make sense once you tweak",
      "something — edit the prompt, change a parameter, add a line — and run it again to see",
      "how the result changes. The code is yours to alter at any time.",
      "",
      "## 💬 Along the way",
      "",
      "We'll **pause to ask you some questions** during the course — to check your",
      "understanding, get you predicting what the model will do, and spark discussion.",
      "Take a moment to think before you run the code; that's where the learning happens.",
      "",
      "**Ready?** Pick the first topic in the sidebar to get started.",
    ].join("\n"),
  },
  {
    id: "raw-response",
    title: "1 · Calling an LLM",
    description: [
      "## what a Responses API call looks like",
      "",
      "A call sends an `input` to the model and returns a structured **response object**.",
      "You choose the model (your `deployment`), pass your input, and get back the generated",
      "text along with metadata like the token `usage`.",
      "",
      "In the steps below you'll run a real call, read the answer, peek at the raw response,",
      "and work out what the call cost.",
    ].join("\n"),
    defaultCode: topic01DefaultCode,
    question: {
      kind: "tokens",
      prompt: "How many tokens did this call cost? (Look at the raw response & usage.)",
      explanation: [
        "## 🔤 What is a token?",
        "",
        "A **token** is the unit a language model reads and writes in — not a whole word and not a",
        "single character, but a chunk of text. Common words are often one token, while longer or",
        "rarer words split into several (for example `tokenization` might become `token` + `ization`).",
        "As a rough rule of thumb, **1 token ≈ 4 characters**, or about **¾ of a word** in English.",
        "",
        "The model turns your text into tokens, does all its work in tokens, and turns tokens back",
        "into text. Everything you send and everything it generates is measured — and billed — in tokens.",
        "",
        "## 🧮 How tokens are counted",
        "",
        "`total_tokens` is everything the request cost — the sum of the input and output tokens:",
        "",
        "- **Input tokens** — the tokens in what you *sent*: your prompt and any context.",
        "Shown as `usage.input_tokens`.",
        "- **Output tokens** — the tokens the model *generated* in its reply.",
        "Shown as `usage.output_tokens`.",
        "- **Cached tokens** — a subset of the input the service had seen recently and served",
        "from cache (faster and cheaper). Shown as `usage.input_tokens_details.cached_tokens`;",
        "they are already counted inside `input_tokens`.",
        "- **Reasoning tokens** — for reasoning models, internal \"thinking\" tokens produced",
        "before the visible answer. They count as output but aren't shown in the text. Shown as",
        "`usage.output_tokens_details.reasoning_tokens`; already counted inside `output_tokens`.",
        "",
        "So: `total_tokens = input_tokens + output_tokens`, where cached is part of the input and",
        "reasoning is part of the output.",
        "",
        "## 💰 Why the types are priced differently",
        "",
        "Not every token costs the same — pricing reflects how much work each one takes:",
        "",
        "- **Output tokens cost more than input tokens** (often several times more). Reading your",
        "input is cheap, but generating each output token means running the full model once per",
        "token, one after another — the expensive part.",
        "- **Cached input tokens are heavily discounted.** When the start of your prompt was seen",
        "recently, the model reuses that already-processed work instead of recomputing it, so those",
        "tokens are billed at a fraction of the normal input price.",
        "- **Reasoning tokens are billed as output**, because the model genuinely generates them —",
        "you pay for that hidden \"thinking\" even though it never appears in the answer.",
        "",
        "## Reading material",
        "",
        "- [Claude model pricing](https://platform.claude.com/docs/en/about-claude/pricing)",
        "- [Understanding tokens](https://learn.microsoft.com/en-us/dotnet/ai/conceptual/understanding-tokens)",
      ].join("\n"),
    },
  },
  {
    id: "system-prompt",
    title: "2 · System & user prompts",
    description: [
      "## a system prompt shapes the whole conversation",
      "",
      "Most chats are more than a single question. A **system prompt** sets the assistant's role,",
      "tone, and rules up front; the **user prompt** is the actual request. The model reads both",
      "and answers in the style the system prompt established.",
      "",
      "Here the system prompt makes the assistant overly happy. Run it and read the answer — then",
      "run it again and watch what changes.",
    ].join("\n"),
    defaultCode: topic02DefaultCode,
    question: {
      kind: "text",
      prompt: "Run the code again and notice the output changes. What causes this?",
      rubric:
        "The answer is correct if it identifies that the LLM is non-deterministic / " +
        "probabilistic — e.g. it samples from a probability distribution over tokens, or " +
        "names randomness, sampling, or temperature as the cause of the varying output. " +
        "Simply restating that 'the output is different' without giving a cause is NOT correct. " +
        "Be lenient about exact wording and synonyms.",
      keywords: [
        "non-deterministic",
        "nondeterministic",
        "non deterministic",
        "not deterministic",
        "random",
        "probabil",
        "stochastic",
        "temperature",
        "sampl",
      ],
      explanation: [
        "## 🎭 System prompt vs user prompt",
        "",
        "A conversation is a list of messages, each tagged with a **role**:",
        "",
        "- **System prompt** — sets the assistant's persona, tone, and rules *before* the chat",
        "starts. You (the developer) write it, the end user doesn't normally see it, and it stays in",
        "effect for the whole conversation. Here it made every reply overly happy.",
        "- **User prompt** — the actual request or message from the person using the app.",
        "",
        "Same model and same user question, but changing the system prompt changes *how* it answers.",
        "That's why the system prompt is the main tool for controlling style, persona, and behaviour —",
        "the user prompt is *what* to do, the system prompt is *how* to do it.",
        "",
        "## 🎲 Why the output changes each run",
        "",
        "An LLM is **non-deterministic**. It doesn't return one fixed answer; at each step it predicts",
        "a probability distribution over the next token and *samples* from it. So the very same input",
        "can produce different wording every time you run it.",
        "",
        "The factual answer here (4 × 4 = 16) stays the same, but the phrasing and enthusiasm vary",
        "run to run. A setting called `temperature` controls how much randomness there is — lower",
        "values make output more repetitive and predictable, higher values more varied.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **What else could you do with a system prompt?** Try editing it — make the assistant",
        "terse, formal, a pirate, or have it always reply in JSON. What can it control, and what can't it?",
        "- **Find the `temperature` setting in the raw response.** Open *Show raw response & usage*",
        "and look through the object: what value is `temperature`, and what other fields do you notice?",
        "- **What are the implications of an LLM being non-deterministic?** Think about testing,",
        "reproducibility, caching, and when you'd want low randomness versus high.",
        "",
        "## Reading material",
        "",
        "- [Prompt engineering guide](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/prompt-engineering)",
        "- [The system prompt for Claude models](https://platform.claude.com/docs/en/release-notes/system-prompts#claude-opus-4-8)",
      ].join("\n"),
    },
  },
  {
    id: "state",
    title: "3 · State & memory",
    description: [
      "## a model has no memory of its own",
      "",
      "Every request to the model is completely independent — it remembers **nothing** from a",
      "previous call. There's no built-in \"conversation\". Watch what happens when we tell it our",
      "name in one call and ask for it in the next.",
    ].join("\n"),
    defaultCode: topic03DefaultCode,
    question: {
      kind: "text",
      prompt:
        "The second call didn't know your name. How do we fix this so the model can hold a conversation?",
      rubric:
        "Correct if the answer is about giving the model the conversation so far: storing/keeping " +
        "the previous messages and sending them with each request — i.e. maintaining chat history, " +
        "conversation context, or memory. Mentioning history, memory, context, or resending prior " +
        "messages all count. Merely saying 'it forgot' or 'use a better prompt' without the idea of " +
        "supplying the past messages is NOT correct. Be lenient about exact wording.",
      keywords: [
        "history",
        "memory",
        "store",
        "stored",
        "storing",
        "context",
        "previous message",
        "past message",
        "prior message",
        "conversation",
        "messages",
        "remember",
        "persist",
      ],
      explanation: [
        "Right — the model only sees what's in the **current** request, so we have to keep the",
        "conversation ourselves and send it back every time. Below we keep an in-memory list of",
        "messages and pass the whole history with each call. Run it and watch it remember.",
      ].join("\n"),
    },
    followUp: {
      title: "Now give it memory",
      intro: [
        "The model still has no memory — **we** give it one. We keep a `history` array of messages",
        "and send the whole conversation on every call, so the second request already contains",
        '"My name is Sam".',
      ].join("\n"),
      code: topic03FixedCode,
      explanation: [
        "## 🧠 Conversations are built by you",
        "",
        "The model is stateless, so a real conversation isn't something it maintains — **you** are.",
        "Your app keeps the previous messages and resends them every turn; that replay is what feels",
        "like \"memory\". Here we used a simple in-memory array.",
        "",
        "## 🗄️ How and where to store history",
        "",
        "An in-memory array only lasts for one run of one process — it's gone on restart and isn't",
        "shared between servers or users. Real apps must decide **how and where** to persist a",
        "conversation: a database, a cache like Redis, or per-user session storage — keyed per",
        "user/conversation, and for how long to keep it. That's a design decision you own.",
        "",
        "## 💸 The effect on tokens and cost",
        "",
        "Because you resend the whole history each turn, the **input grows as the conversation gets",
        "longer**. By the 20th message you're sending all ~20 messages (plus any system prompt) as",
        "input every single call — so input tokens, latency, and cost climb with conversation length.",
        "That's why long chats are usually **trimmed, summarised, or windowed** to the most relevant",
        "messages to cap the token count, and why prompt caching (the discounted repeated prefix from",
        "Topic 1) matters so much here.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Roles in the output.** The fixed version introduced message **roles** (`user`,",
        "`assistant`). Open *Show raw response & usage* and find the `output` section — what `role`",
        "is shown on the message the model produced?",
        "- **Tip — start a fresh session for a new topic.** When you want to talk about something",
        "different, start a **new conversation** instead of appending to the old one. That resets the",
        "history, so the model isn't distracted by unrelated context *and* you stop the token count",
        "(and cost) from accumulating with every extra message.",
      ].join("\n"),
    },
  },
  {
    id: "tools",
    title: "5 · Tools & live data",
    description: [
      "## a model can't see the current world",
      "",
      "A model is frozen at its **training cutoff** — it has no clock, no internet, and no access to",
      "your data. Ask it something that depends on *right now* and it can only guess or refuse. Try",
      "asking it for the current date and time.",
    ].join("\n"),
    defaultCode: topic04DefaultCode,
    question: {
      kind: "text",
      prompt: "The model couldn't give the real date and time. How can we get it accurate, live information?",
      rubric:
        "Correct if the answer is about giving the model access to real data: using a tool / " +
        "function calling, connecting it to an external source or API, or injecting/providing the " +
        "current information into the prompt/context (including retrieval / RAG). Naming tools, " +
        "function calling, APIs, plugins, providing or injecting context, or RAG all count. Merely " +
        "repeating that 'it doesn't know' without a way to supply the data is NOT correct. Be " +
        "lenient about exact wording.",
      keywords: [
        "tool",
        "function",
        "api",
        "inject",
        "provide",
        "context",
        "retriev",
        "plugin",
        "external",
        "look up",
        "search",
        "mcp",
        "rag",
        "feed",
      ],
      explanation: [
        "Right — the model can't fetch live data itself, but we can hand it a **tool** it may call.",
        "Below we add a `get_current_datetime` tool: the model asks for it, we run it, feed the",
        "result back, and it answers with the real time. Run it.",
      ].join("\n"),
    },
    followUp: {
      title: "Now add a tool",
      intro: [
        "We give the model a **tool** — a function it can ask us to run. We describe",
        "`get_current_datetime`; the model decides to call it, we execute it and pass the result",
        "back, then it answers using the live value.",
      ].join("\n"),
      code: topic04ToolCode,
      explanation: [
        "## 📅 Why it couldn't tell the time",
        "",
        "An LLM is frozen at its **training cutoff**: it learned from data up to some date and has no",
        "clock, no internet, and no access to your systems. Anything newer than its training — or any",
        "live or private data — is simply unknown to it, so on its own it can only guess or refuse.",
        "",
        "## 🛠️ Tools and context bridge the gap",
        "",
        "Two common ways to give it what it lacks:",
        "",
        "- **Tools (function calling)** — you describe functions the model may call. It doesn't run",
        "them; it asks *you* to, you execute the code (a clock, a database, an API…) and pass the",
        "result back. That's exactly what we just did.",
        "",
        "![Tool calling flow — the application makes the actual function call, not the model](/images/tool-calling-flow.png)",
        "",
        "- **Injecting context** — you fetch the data yourself and put it straight into the prompt",
        "(e.g. \"Today is 2026-06-19. …\"). Simpler, but you choose up front what to include. Doing",
        "this with a search/retrieval step is called **RAG** (retrieval-augmented generation).",
        "",
        "## ⚖️ Don't over-tool",
        "",
        "Every tool you attach is described to the model on **every** call, so each tool's schema adds",
        "**input tokens**. A long list of tools costs more and can **confuse the model** — it may pick",
        "the wrong tool or call one it doesn't need. Give it only the tools the task actually needs.",
        "",
        "## 🔌 MCP servers",
        "",
        "The **Model Context Protocol (MCP)** is an open standard for exposing tools and data to a",
        "model through a server. Instead of hand-wiring each function in your app, you point the model",
        "at an MCP server that advertises its tools and resources — a reusable, shareable way to add",
        "the same capabilities (files, search, databases, SaaS apps) across different apps and models.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Find `tool_choice` in the output.** Open *Show raw response & usage* and look for the",
        "`tool_choice` field — what value do you see? It controls *whether* the model may call a tool:",
        "`\"auto\"` (the default — the model decides), `\"none\"` (never call a tool, just answer),",
        "`\"required\"` (it must call some tool), or a specific `{ type: \"function\", name: \"…\" }`",
        "to force one particular tool. Try setting it on the call and see how the behaviour changes.",
      ].join("\n"),
    },
  },
  {
    id: "structured-output",
    title: "9 · Structured output",
    description: [
      "## getting structured data out, reliably",
      "",
      "Often you don't want prose — you want **data** your code can use: known fields, known types,",
      "a known shape. You can just *ask* for JSON, but the model might wrap it in markdown, add a",
      "comment, rename a field, or change a type. Let's see the problem, then fix it.",
    ].join("\n"),
    defaultCode: topic05DefaultCode,
    question: {
      kind: "text",
      prompt:
        "Asking for JSON didn't give us something we can reliably parse. How do we force the model to return valid JSON in an exact shape?",
      rubric:
        "Correct if the answer is about constraining/enforcing the output format with a schema: " +
        "using structured outputs, a JSON schema, a response format, `text.format` / `response_format`, " +
        "or JSON mode so the model must return valid JSON in a defined shape. Mentioning a schema, " +
        "structured output, JSON mode, or response format all count. Just saying 'ask more clearly' or " +
        "'parse/clean it better' without constraining the model's output is NOT correct. Be lenient " +
        "about exact wording.",
      keywords: [
        "schema",
        "json_schema",
        "structured",
        "response_format",
        "response format",
        "text.format",
        "format",
        "json mode",
        "constrain",
        "grammar",
      ],
      explanation: [
        "Right — instead of hoping, we give the model a **schema** and have it enforce the output.",
        "Below we pass a JSON schema via `text.format`; the model must return valid JSON in exactly",
        "that shape. Run it and parse the result with confidence.",
      ].join("\n"),
    },
    followUp: {
      title: "Now add a schema",
      intro: [
        "We attach a **JSON schema** via `text.format`. With `strict: true` the model is constrained",
        "to return valid JSON that matches the schema exactly — the right fields, the right types,",
        "nothing extra.",
      ].join("\n"),
      code: topic05SchemaCode,
      explanation: [
        "## 🧱 A schema guarantees the shape",
        "",
        "Structured outputs constrain the model so its reply **must** be valid JSON matching the schema",
        "you supply — the exact fields, types, and required keys, with no markdown fences or stray",
        "prose. You define the shape with `text.format: { type: \"json_schema\", schema, strict: true }`,",
        "and `output_text` is clean JSON you can `JSON.parse` without any defensive cleanup.",
        "",
        "## 🆚 Why this beats \"please return JSON\"",
        "",
        "Asking in the prompt is a *request* — the model may still wrap the JSON in a Markdown code",
        "fence, add a comment, rename a field, or change a type, and it varies run to run",
        "(non-determinism, from Topic 2). A schema is a *constraint*: the platform enforces it, so you",
        "stop writing brittle parse-and-hope code.",
        "",
        "## 🧰 Where you'd use it",
        "",
        "Anywhere the output feeds code rather than a human: extracting fields from text, classifying",
        "into fixed categories, building rows for a database, or producing arguments for the next step",
        "in a pipeline. It pairs naturally with tools (Topic 5) — tools take structured *input*,",
        "structured outputs give you structured *output*.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Add a field to the schema** — e.g. an `email` string or a `hobbies` array of strings —",
        "and re-run. The model fills the new shape without you touching the prompt.",
        "- **Constrain a value with an `enum`.** Add a `sentiment` field of `\"positive\" | \"neutral\" |",
        "\"negative\"` and ask it to judge a sentence — the reply can only be one of those.",
        "- **Loosen it.** Remove a field from `required`, or set `strict: false`, and see what changes",
        "about the guarantees.",
      ].join("\n"),
    },
  },
  {
    id: "multimodal",
    title: "11 · Multimodal",
    description: [
      "## models that see, not just read",
      "",
      "Some models are **multimodal** — they handle more than text. A vision-capable model can take",
      "an **image** alongside your words and reason about it. Here we send a photo the model has",
      "never been told about and ask it to describe what it sees.",
    ].join("\n"),
    defaultCode: topic06DefaultCode,
    question: {
      kind: "text",
      prompt: "The model just \"read\" an image. How does sending an image affect the call's token usage and cost?",
      rubric:
        "Correct if the answer recognizes that the image is converted into tokens (image/vision " +
        "tokens) and counts toward input tokens — so it adds to token usage and cost, and that " +
        "larger or higher-resolution/detail images use more tokens. Mentioning that images become " +
        "tokens, add input tokens, or cost more (especially bigger/high-detail images) all count. " +
        "Saying images are free or don't affect tokens is incorrect. Be lenient about wording.",
      keywords: [
        "token",
        "input token",
        "image token",
        "vision token",
        "more token",
        "cost",
        "resolution",
        "size",
        "bigger",
        "larger",
        "pixels",
        "tiles",
        "patches",
        "detail",
      ],
      explanation: [
        "## 🖼️ What \"multimodal\" means",
        "",
        "A multimodal model handles more than text. This one accepts **images** alongside your words —",
        "you just saw it describe a photo it was never told about. Other models also take **audio** or",
        "**video**, and some can **generate** images or audio as output, not only consume them.",
        "",
        "## 🔢 Images are tokens too",
        "",
        "Under the hood the image is turned into **tokens**, just like text (Topic 1): the model splits",
        "it into patches/tiles and encodes them, so an image adds to your **input tokens** — and a",
        "larger or higher-detail image costs more. Open *Show raw response & usage* and look at",
        "`usage.input_tokens`: it's far higher than a short text-only prompt. Images aren't free.",
        "",
        "## 🎛️ Input vs output modalities",
        "",
        "\"Multimodal\" describes what a model can take *in* and put *out*, and these differ per model.",
        "our chat model reads text + images but replies in **text**. Image-generation and speech models do",
        "the reverse. Always check which modalities your chosen deployment actually supports.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Compare the token cost.** Note `usage.input_tokens` here, then run a plain text question",
        "from an earlier topic — how much did the image add?",
        "- **Ask something specific.** Change the question to \"What colours dominate this image?\" or",
        "\"Is this indoors or outdoors?\" — the model reasons over the pixels, not a stored caption.",
        "- **Swap the image.** Replace the `image_url` with another public image URL that contains text and ask what it says.",
        "",
        "## Reading material",
        "",
        "[What is multimodal AI?](https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-multimodal-ai)",
      ].join("\n"),
    },
  },
  {
    id: "rag",
    title: "8 · Retrieval (RAG)",
    description: [
      "## grounding the model in your own data",
      "",
      "A model only knows its training data — not your private documents, internal policies, or",
      "anything specific to you. Ask it about that and it will often **make something up** rather",
      "than admit it doesn't know. Let's see that happen, then fix it.",
    ].join("\n"),
    defaultCode: topic07DefaultCode,
    question: {
      kind: "text",
      prompt:
        "The model invented an answer about our internal policy. How can we get it to answer correctly from our own documents?",
      rubric:
        "Correct if the answer is about retrieving the relevant document(s) and providing/injecting " +
        "that text into the prompt as context so the model answers from it — i.e. the idea behind " +
        "RAG (retrieval-augmented generation): look the data up and put it in the context/prompt, " +
        "optionally via embeddings/vector search. Mentioning retrieval, RAG, injecting/providing " +
        "context or documents, grounding, or a knowledge base all count. Saying 'fine-tune the " +
        "model' is a different approach — accept it only if they also mention supplying the data; " +
        "merely 'ask better' or 'it should know' is NOT correct. Be lenient about wording.",
      keywords: [
        "rag",
        "retriev",
        "inject",
        "provide",
        "context",
        "document",
        "knowledge base",
        "embedding",
        "vector",
        "search",
        "ground",
        "lookup",
        "look up",
      ],
      explanation: [
        "Right — we **retrieve** the relevant text and **inject** it into the prompt, so the model",
        "answers from our documents instead of guessing. Below we use **embeddings** to find the most",
        "relevant document by meaning, then ground the answer in it. Run it.",
      ].join("\n"),
    },
    followUp: {
      title: "Now add retrieval",
      intro: [
        "This is **RAG — retrieval-augmented generation**, done with **embeddings**. We turn each",
        "document and the question into vectors, rank documents by **cosine similarity**, inject the",
        "best match as context, and tell the model to answer only from it. Notice the question shares",
        "almost no words with the document — embeddings match on *meaning*, not keywords.",
      ].join("\n"),
      code: topic07RagCode,
      explanation: [
        "## 📚 What RAG is",
        "",
        "**Retrieval-Augmented Generation** has three steps: **retrieve** the text relevant to the",
        "question, **augment** the prompt by injecting it as context, then let the model **generate**",
        "an answer grounded in that context. The model's weights never change — you're just feeding it",
        "the right information at question time.",
        "",
        "## 🧭 Embeddings & similarity",
        "",
        "An **embedding** turns text into a vector — a list of numbers that captures its *meaning*, so",
        "similar ideas sit close together. We embed every document and the question, then score each",
        "doc by **cosine similarity** (how aligned the vectors are). That's why \"paid time off when",
        "you join\" retrieved the **vacation days** doc despite sharing no keywords — a plain keyword",
        "search would have missed it.",
        "",
        "## 🔍 At real scale",
        "",
        "Here we embed three short docs on every run. Real systems split large documents into **chunks**,",
        "embed them **once**, and store the vectors in a **vector database** that returns the top-k",
        "nearest matches in milliseconds — so you don't re-embed the whole corpus per question.",
        "",
        "## ✅ Why it helps",
        "",
        "RAG **grounds** answers in real data, which cuts hallucination, lets the model use **private**",
        "or **up-to-date** information without retraining, and lets you **cite sources**. It's usually",
        "cheaper and faster to update a document store than to fine-tune a model.",
        "",
        "## ⚖️ Trade-offs",
        "",
        "The injected context is **input tokens** (Topic 1), so retrieving too much costs more and can",
        "bury the answer; retrieving the *wrong* text gives a confident wrong answer (garbage in,",
        "garbage out). The art is good chunking and retrieving *few, relevant* passages — and telling",
        "the model to say \"I don't know\" when the context doesn't cover the question.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Read the scores.** The log prints each document's cosine similarity — how far ahead is the",
        "top match? Try a question that's relevant to a *different* document and watch the ranking flip.",
        "- **Ask something not in the docs** (e.g. \"What's the parental leave policy?\"). With the",
        "\"answer only from context\" instruction, the model should say it doesn't know instead of",
        "inventing — compare that to this topic's first run.",
        "- **Add a document** to the knowledge base and ask about it. Notice you didn't retrain anything —",
        "you just embedded one more string.",
        "",
        "## Reading material",
        "",
        "[Deep dive into RAG](https://www.promptingguide.ai/research/rag)",
      ].join("\n"),
    },
  },
  {
    id: "reasoning",
    title: "4 · Reasoning models",
    description: [
      "## models that think before they answer",
      "",
      "Some models are **reasoning models** — instead of replying immediately, they first work",
      "through the problem step by step *internally*, then give a final answer. This makes them much",
      "stronger on hard, multi-step tasks. We'll ask `gpt-5` a classic trick question and peek at the",
      "hidden thinking in the token usage.",
    ].join("\n"),
    defaultCode: topic08DefaultCode,
    question: {
      kind: "text",
      prompt:
        "The visible answer was tiny, yet `output_tokens` was much larger. Where did the extra output tokens go?",
      rubric:
        "Correct if the answer recognizes the extra output tokens are the model's internal reasoning / " +
        "thinking tokens — the step-by-step reasoning (chain of thought) the model generates before the " +
        "final answer, which is hidden from the visible text but still counted/billed as output tokens. " +
        "Mentioning reasoning tokens, thinking tokens, internal reasoning, or chain of thought all count. " +
        "Saying the tokens are the input, the prompt, or the visible answer is incorrect. Be lenient about wording.",
      keywords: [
        "reasoning",
        "thinking",
        "think",
        "internal",
        "chain of thought",
        "chain-of-thought",
        "hidden",
        "reasoning_token",
        "reasoning token",
        "step",
      ],
      explanation: [
        "## 🧠 What a reasoning model does",
        "",
        "A reasoning model (like `gpt-5`, or the o-series) doesn't answer straight away — it first",
        "generates a private chain of \"thinking\" to work through the problem, then writes the final",
        "answer. That's why it's far stronger on multi-step tasks: maths, logic, planning, debugging.",
        "Notice it dodged the trap answer ($0.10) and correctly returned **$0.05**.",
        "",
        "## 🪙 Reasoning tokens",
        "",
        "That thinking is real generated text — **reasoning tokens** — but you don't see it; only the",
        "final answer comes back. They show up in `usage.output_tokens_details.reasoning_tokens` and",
        "are **billed as output tokens** (Topic 1). That's why `output_tokens` was far bigger than the",
        "short answer suggests — most of it was hidden reasoning.",
        "",
        "## 🎭 It isn't real \"thinking\"",
        "",
        "Don't take the word *reasoning* too literally. The model isn't consciously deducing or",
        "understanding anything — the chain of thought is just **more generated text**, produced by the",
        "exact same next-token prediction as any other output (Topic 2), only pointed inward before the",
        "answer. It *usually* helps because writing the steps out gives the model more relevant context",
        "to condition its final answer on — but it's not a guarantee of correctness. The reasoning can",
        "look perfectly logical and still be wrong, skip a step, or not even match the final answer",
        "(models can rationalise after the fact). Treat it as a **technique that improves the odds** on",
        "hard problems, not as a mind that *knows* it is right.",
        "",
        "## 🎚️ Reasoning effort",
        "",
        "You can dial how hard it thinks with `reasoning: { effort: \"low\" | \"medium\" | \"high\" }`.",
        "More effort → more reasoning tokens → usually better answers on hard problems, but higher cost",
        "and latency. Less effort is faster and cheaper for easy questions.",
        "",
        "## ⚖️ When to use one",
        "",
        "Reach for a reasoning model on genuinely hard, multi-step problems. For simple tasks",
        "(formatting, short Q&A, extraction) a regular model like `gpt-5-chat` is faster and cheaper —",
        "paying for reasoning you don't need just adds latency and cost.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Watch the reasoning grow.** Add `reasoning: { effort: \"high\" }` to the call and compare",
        "`reasoning_tokens` with the default run.",
        "- **Try an easy question.** Ask \"What's the capital of France?\" — how many reasoning tokens",
        "does it spend on something trivial?",
        "- **Compare models.** Change `model` to the regular `deployment` (the non-reasoning chat",
        "model) and ask the bat-and-ball question — how does its `usage` differ (any reasoning tokens)?",
        "",
        "## Reading material",
        "",
        "[A Visual Guide to Reasoning LLMs](https://newsletter.maartengrootendorst.com/p/a-visual-guide-to-reasoning-llms)",
      ].join("\n"),
    },
  },
  {
    id: "streaming",
    title: "10 · Streaming",
    description: [
      "## show the answer as it's written",
      "",
      "By default you wait for the whole response, then it appears at once. With **streaming** the",
      "model sends its answer in small chunks as it generates them, so text starts appearing",
      "immediately. Run this and watch the haiku type itself out, word by word.",
    ].join("\n"),
    defaultCode: topic09DefaultCode,
    question: {
      kind: "text",
      prompt:
        "Streaming gives the exact same final answer, at the same total cost. So why stream it at all?",
      rubric:
        "Correct if the answer is about user experience / perceived responsiveness: streaming shows " +
        "partial output as it's generated so the user sees the first words almost immediately (low " +
        "time-to-first-token), can start reading sooner, and the app feels faster / more responsive — " +
        "especially for long responses or chat UIs. Mentioning perceived latency, responsiveness, UX, " +
        "showing progress, time-to-first-token, or 'feels faster / less waiting' all count. Saying it " +
        "is actually faster overall or cheaper is incorrect (totals are the same). Be lenient about wording.",
      keywords: [
        "perceiv",
        "latency",
        "responsive",
        "ux",
        "user experience",
        "progress",
        "sooner",
        "wait",
        "first token",
        "feel",
        "experience",
        "immediately",
        "spinner",
      ],
      explanation: [
        "## ⚡ What streaming changes",
        "",
        "Without streaming you wait for the entire answer, then it appears all at once. With streaming",
        "the model sends the response in small chunks (roughly token by token) as it generates them, so",
        "text shows up right away and keeps flowing. The **total time and token cost are the same** —",
        "what changes is the *experience*.",
        "",
        "## 🕒 Why it matters",
        "",
        "The model still takes just as long to finish, but the user sees the first words almost instantly",
        "(low **time-to-first-token**) and can start reading while the rest arrives. For anything longer",
        "than a sentence — or a chat UI — that makes the app feel far more responsive than staring at a",
        "spinner.",
        "",
        "## 🔧 How it works here",
        "",
        "`client.responses.stream(...)` returns an async iterable of events. We loop with `for await`,",
        "and on each `response.output_text.delta` we append `event.delta` to the screen; the final",
        "`usage` arrives on the `response.completed` event. (Under the hood it's server-sent events —",
        "the same mechanism this whole app uses to stream every run's output back to your browser.)",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Ask for something long** (e.g. \"Explain how rainbows form in 5 sentences.\") and feel the",
        "difference between watching it stream versus waiting for one big block.",
        "- **Find the usage.** It arrives on the `response.completed` event — the same totals a",
        "non-streamed call would report.",
        "- **Streaming + tools.** If the model needs to call a tool (Topic 5) partway through, how might",
        "that interrupt the flow of streamed text?",
        "",
        "## Reading material",
        "",
        "- [Azure OpenAI streaming](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/streaming)",
        "- [Server-sent events (MDN)](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events)",
      ].join("\n"),
    },
  },
  {
    id: "mcp",
    title: "7 · MCP servers",
    description: [
      "## tools without the wiring",
      "",
      "In Topic 5 you hand-wrote a tool and ran the call loop yourself. **MCP** (the Model Context",
      "Protocol) is a standard way to expose a whole *set* of tools from a **server**, so the model",
      "can discover and use them with almost no code on your side.",
      "",
      "Here we point the call at the public **Microsoft Learn** MCP server and ask a docs question.",
      "We never define a tool or run a loop — the model lists the server's tools and calls them itself.",
    ].join("\n"),
    defaultCode: topic10DefaultCode,
    question: {
      kind: "text",
      prompt:
        "Compared with Topic 5, we wrote no tool schema and no call loop — yet the model still used a tool. What did MCP do for us?",
      rubric:
        "Correct if the answer captures that MCP provides the tools from a server in a standard way so " +
        "the model can discover/list and call them automatically — i.e. the server advertises its tools " +
        "(and how to call them), removing the need to hand-define each tool schema and run the call loop " +
        "yourself, and making the same tools reusable across apps/models. Mentioning auto-discovery, a " +
        "standard protocol/interface, the server exposing/advertising tools, or reusability all count. " +
        "Saying 'nothing' or 'it's just a normal API call' is incorrect. Be lenient about wording.",
      keywords: [
        "discover",
        "list",
        "standard",
        "protocol",
        "server",
        "expose",
        "advertis",
        "reusable",
        "interface",
        "wiring",
        "automatic",
        "no schema",
        "no loop",
      ],
      explanation: [
        "## 🔌 What MCP is",
        "",
        "The **Model Context Protocol (MCP)** is an open standard for connecting models to tools and",
        "data through a **server**. The server *advertises* what it offers — its tools, their inputs,",
        "and any resources — in a standard shape. Any MCP-aware client can connect, ask \"what can you",
        "do?\", and call those capabilities without custom glue. Think of it as a **USB-C port for AI",
        "tools**: one standard plug instead of a custom cable per device.",
        "",
        "## 🆚 How it differs from plain tool calling",
        "",
        "Topic 5's tools and MCP both end in the model calling a function — the difference is **who",
        "defines and hosts them**:",
        "",
        "- **Plain tool calling** — *you* write each tool's schema in your app, and *you* run the loop",
        "(execute the function, feed the result back). Great for a few app-specific functions, but every",
        "app re-implements them.",
        "- **MCP** — the **server** owns the tools and describes them in a standard way. The model lists",
        "them and calls them; here the platform even ran the calls for us. The same server works with",
        "**any** app or model that speaks MCP — write once, reuse everywhere.",
        "",
        "In the output you saw `mcp_list_tools` (the model discovering what the server offers) and",
        "`mcp_call` (it invoking one) — steps you wrote by hand in Topic 5.",
        "",
        "## 🏠 Local vs 🌐 remote MCP servers",
        "",
        "- **Local** — the server runs on your own machine (often launched as a subprocess and spoken to",
        "over stdio). Ideal for accessing local files, your shell, a database on your network, or",
        "anything private that shouldn't leave your environment.",
        "- **Remote** — the server is hosted over HTTP, like the Microsoft Learn server we just used.",
        "No install, centrally maintained, and shareable — but you're sending your request to a third",
        "party, so trust, auth, and privacy matter.",
        "",
        "## ⚠️ Things to weigh",
        "",
        "MCP tools are still tools: their definitions cost **input tokens** (Topic 5's \"don't over-tool\"",
        "applies), and a remote server is **external code you don't control** — only connect to servers",
        "you trust, and use approvals/auth for anything sensitive. We set `require_approval: \"never\"`",
        "here to keep the demo one-click; in a real app you'd gate tool calls behind approval.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Ask a different docs question** (e.g. \"How do I create a storage account with the Azure",
        "CLI?\") and watch it pull the answer from the Microsoft Learn server.",
        "- **Inspect the calls.** Open *Show raw response & usage* and find the `mcp_list_tools` and",
        "`mcp_call` items — what tools did the server expose, and which did the model choose?",
        "- **Local vs remote.** Which of your own systems would you expose over a *local* MCP server,",
        "and which over a *remote* one — and why?",
        "",
        "## Reading material",
        "",
        "- [MCP introduction](https://modelcontextprotocol.io/docs/getting-started/intro)",
        "- [MCP servers](https://github.com/modelcontextprotocol/servers)",
        "- [MCP specification](https://spec.modelcontextprotocol.io/)",
      ].join("\n"),
    },
  },
  {
    id: "context-window",
    title: "13 · Context windows",
    description: [
      "## the model can only hold so much at once",
      "",
      "A model has a fixed **context window** — the maximum number of tokens it can work with in one",
      "call. Crucially, that budget is shared by **everything**: the system prompt, the conversation",
      "history, any retrieved context or tool definitions, your question — *and* the answer it",
      "generates. Run out of room and the response gets cut off or the request fails.",
      "",
      "To show the budget concretely we cap the *output* far too low and watch the answer stop",
      "mid-sentence. Run it and look at `status`.",
    ].join("\n"),
    defaultCode: topic11DefaultCode,
    question: {
      kind: "text",
      prompt:
        "The answer stopped mid-sentence with status \"incomplete\". The window is shared between input and output — so what eats into the budget left for the answer in a real app?",
      rubric:
        "Correct if the answer identifies things that consume the shared context budget / input tokens, " +
        "leaving less room for output: e.g. the conversation history (Topic 3), the system prompt, " +
        "retrieved/injected context or documents (RAG, Topic 8), tool definitions (Topic 5), few-shot " +
        "examples, or a long prompt/question. Naming any of history, system prompt, RAG/retrieved " +
        "context, tools, examples, or 'a big input/prompt' counts. Saying 'nothing' or only repeating " +
        "'the output' is incorrect. Be lenient about wording.",
      keywords: [
        "history",
        "conversation",
        "system prompt",
        "context",
        "retriev",
        "rag",
        "document",
        "tool",
        "example",
        "few-shot",
        "few shot",
        "prompt",
        "input",
        "instruction",
      ],
      explanation: [
        "Right — everything you send shares the same budget. Below we simply give the output enough",
        "room so the answer completes. But in a real app the *input* side is what usually grows. Run",
        "the fixed version, then read on.",
      ].join("\n"),
    },
    followUp: {
      title: "Now raise the limit",
      intro: [
        "The cap was the problem — raise `max_output_tokens` and the answer finishes (`status:",
        "\"completed\"`). The real lesson is that input and output draw from **one shared budget**.",
      ].join("\n"),
      code: topic11FixedCode,
      explanation: [
        "## 📏 What the context window is",
        "",
        "The **context window** is the maximum number of tokens a model can consider in a single call —",
        "and it covers **input + output together**, not just one side. Every token of system prompt,",
        "history, retrieved context, tool definitions, your question, and the generated answer comes out",
        "of the same pool. Different models have very different window sizes.",
        "",
        "## 🧮 Everything competes for the budget",
        "",
        "This connects every earlier topic: conversation **history** (Topic 3), **retrieved documents**",
        "(RAG, Topic 8), **tool definitions** (Topic 5), the **system prompt** (Topic 2), and examples",
        "all live in the input — so the more you add, the less room is left for the answer. We forced",
        "the issue from the output side with `max_output_tokens`, but in practice it's usually a bloated",
        "*input* that crowds things out.",
        "",
        "## 🚧 What happens at the limit",
        "",
        "Two failure modes: the **output** can be truncated mid-text — you saw `status: \"incomplete\"`",
        "with `incomplete_details.reason = \"max_output_tokens\"` — or the **input** can be too big to",
        "fit at all, which the API rejects with an error. Either way you don't get the answer you wanted.",
        "",
        "## 🧭 Working within it",
        "",
        "This is why long chats are **trimmed, summarised, or windowed** (Topic 3), why RAG retrieves",
        "*few, relevant* passages instead of whole documents (Topic 8), and why you give only the tools",
        "you need (Topic 5). A bigger window helps but costs more per call (more input tokens, Topic 1) —",
        "managing the budget is part of building with LLMs.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Find the floor.** Lower `max_output_tokens` until even a short answer can't finish — when",
        "does `status` flip to `incomplete`?",
        "- **Watch input grow.** Imagine a 50-message chat plus three retrieved documents: which part",
        "of the budget is filling up, and what would you trim first?",
        "- **Right-size the window.** When would you pick a model with a much larger context window, and",
        "what's the cost of doing so on every call?",
        "",
        "## Reading material",
        "",
        "[Smarter Context Management](https://blog.jetbrains.com/research/2025/12/efficient-context-management/)",
      ].join("\n"),
    },
  },
  {
    id: "image-generation",
    title: "12 · Image generation",
    description: [
      "## models that draw, not write",
      "",
      "So far the model has *read* images (Topic 11) and produced text. **Image-generation models** do",
      "the opposite: you give a text **prompt** and they return a **picture**. Different model, different",
      "API call — `client.images.generate(...)` instead of `responses.create(...)`.",
      "",
      "Run it and watch an image appear from a sentence of description. Then edit the prompt and run",
      "again.",
    ].join("\n"),
    defaultCode: topic12DefaultCode,
    question: {
      kind: "text",
      prompt:
        "We called `client.images.generate` instead of the usual `responses.create`, and got back a picture, not text. Why a different model and endpoint?",
      rubric:
        "Correct if the answer recognizes that image generation is a different *kind* of model / " +
        "modality with a different output (pixels/an image, not text tokens), so it needs its own " +
        "dedicated model and API endpoint rather than the text/chat one — a text model can't produce " +
        "images. Mentioning a specialised/dedicated image model, a different modality, different output " +
        "type, or 'text models only produce text' all count. Saying it's the same model or arbitrary is " +
        "incorrect. Be lenient about wording.",
      keywords: [
        "different model",
        "image model",
        "special/specialised",
        "dedicated",
        "modality",
        "different output",
        "pixels",
        "image",
        "not text",
        "diffusion",
        "trained",
        "endpoint",
      ],
      explanation: [
        "## 🎨 A different kind of model",
        "",
        "Generating an image is a fundamentally different task from predicting text, so it uses a",
        "**dedicated image model** (here `imageDeployment`, e.g. `gpt-image-1`) and a different endpoint:",
        "`client.images.generate(...)`. A text model like our chat deployment only ever outputs tokens — it cannot",
        "produce pixels. \"Multimodal\" (Topic 11) was about what a model can take *in*; this is about what",
        "it puts *out*.",
        "",
        "## 🖼️ How the result comes back",
        "",
        "The response isn't text — it's the picture itself, returned as **base64-encoded image data**",
        "(`res.data[0].b64_json`). The lesson's `showImage(...)` helper wraps that into a data URL and",
        "renders it. (Some image models can instead return a temporary `url`.) There's no `output_text`",
        "to read here.",
        "",
        "## 💲 How it's billed",
        "",
        "Image models aren't priced like text. Cost is typically **per image**, varying with the",
        "**resolution/size** and quality you request — not by counting output tokens. Bigger images cost",
        "more, so request the size you actually need.",
        "",
        "## ⚠️ Worth knowing",
        "",
        "Generation takes longer than a text reply (often several seconds), results are **non-deterministic**",
        "(Topic 2) — the same prompt yields a different picture each run — and the prompt wording matters",
        "a lot. Providers also apply content filters to what can be generated.",
        "",
        "## 🔀 How ChatGPT hides this from you",
        "",
        "When you ask ChatGPT to \"draw me a cat\" and then \"explain what's in the image\" in the same",
        "chat, it feels like one seamless model. It isn't. ChatGPT uses a **model router** that inspects",
        "your message and silently dispatches it to whichever specialist model fits best — the text/reasoning",
        "model for conversation, the image-generation model for \"draw me…\", the vision model for",
        "\"what's in this image?\", and so on. You see one chat window; behind it is a fleet of models",
        "and a router deciding which one handles each turn.",
        "",
        "This is exactly what we've been building piece by piece: tools (Topic 5), multiple models,",
        "different endpoints. A polished product just wraps all of that in one interface so users",
        "never see the seams.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Change the style.** Edit the prompt — try \"as a watercolour painting\" or \"as a 3D render\"",
        "— and see how much the wording steers the result.",
        "- **Change the size.** Request a different `size` and think about how that maps to cost.",
        "- **Run it twice.** The same prompt gives a different image each time — the visual version of the",
        "non-determinism you saw with text in Topic 2.",
      ].join("\n"),
    },
  },
  {
    id: "evals",
    title: "15 · Guardrails, evals & tests",
    description: [
      "## you can't ship LLM features on vibes",
      "",
      "LLMs are non-deterministic (Topic 2) and their inputs are open-ended, so \"it worked when I",
      "tried it\" tells you almost nothing. Here's the trap: we run a sentiment classifier on **one**",
      "nice example, it looks right, and we feel confident. Run it.",
    ].join("\n"),
    defaultCode: topic13DefaultCode,
    question: {
      kind: "text",
      prompt:
        "It classified that one message correctly. Why isn't a single manual check enough to trust this feature in production?",
      rubric:
        "Correct if the answer recognizes that one example doesn't prove the feature works across the " +
        "many/varied/edge-case inputs real users send — especially given non-determinism — so you need " +
        "systematic testing: an eval set / test suite of many labelled cases run and scored " +
        "automatically, to catch failures and regressions. Mentioning evals, a test set, many/edge " +
        "cases, regressions, measuring accuracy across inputs, or that one sample isn't representative " +
        "all count. Saying 'it's fine' or 'just read the output' is incorrect. Be lenient about wording.",
      keywords: [
        "eval",
        "test",
        "many",
        "cases",
        "edge case",
        "dataset",
        "regression",
        "varied",
        "sample",
        "representative",
        "systematic",
        "accuracy",
        "measure",
        "coverage",
        "non-deterministic",
      ],
      explanation: [
        "Exactly — one passing example proves nothing about the next input. Below we build a small",
        "**eval**: a set of labelled cases, run automatically and scored. Run it and watch a case fail —",
        "that's the eval catching what a spot-check would miss.",
      ].join("\n"),
    },
    followUp: {
      title: "Now run an eval",
      intro: [
        "An **eval** runs the feature over a labelled test set and scores it. Each case has a known",
        "correct answer; we compare the model's output and report a pass rate. The enum structured",
        "output (Topic 9) also acts as a **guardrail** — the model can only return an allowed label.",
      ].join("\n"),
      code: topic13EvalCode,
      explanation: [
        "## 🛡️ Guardrails",
        "",
        "**Guardrails** are runtime checks that keep a live feature safe and well-formed — on the way",
        "**in** (reject prompt-injection, off-topic, or disallowed requests) and on the way **out**",
        "(validate the shape, filter unsafe content, block leaks). The `enum` schema here is a guardrail:",
        "the output *cannot* be anything but `positive`/`neutral`/`negative`. Guardrails act on **every",
        "real request**, in production.",
        "",
        "## 📊 Evals",
        "",
        "**Evals** measure quality **offline**, before you ship. You assemble a labelled dataset of",
        "representative + tricky inputs, run the feature over all of them, and score the results to get a",
        "number (here, pass rate). That number lets you compare prompts, models, or settings objectively",
        "and catch **regressions** when you change something — the sarcastic case failing is the eval",
        "earning its keep.",
        "",
        "## ✅ Tests & scoring",
        "",
        "LLM tests look like normal tests but **non-determinism (Topic 2) changes how you assert**. Exact",
        "string matching is brittle, so you check **properties** instead: is the label one of the allowed",
        "values, does the JSON parse, does it contain the key fact? For open-ended text where there's no",
        "single right answer, score with an **LLM-as-judge** (exactly how this workshop grades your",
        "free-text answers — `/api/grade`). Run these in CI so a bad change is caught automatically.",
        "",
        "## 🔁 The loop",
        "",
        "Guardrails (protect each live call), evals (measure quality before shipping), and tests (catch",
        "regressions in CI) form a feedback loop: ship → observe failures → add them as new eval cases →",
        "improve → re-measure. The eval set grows into your definition of \"working\".",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Grow the test set.** Add a tricky case (sarcasm, mixed sentiment, another language) and",
        "re-run — does the score drop? Real eval sets grow with every bug you find.",
        "- **Judge open-ended output.** Sentiment has a known label, but how would you score a feature",
        "that *summarises* text, where there's no single correct answer? (Hint: an LLM-as-judge — how",
        "this workshop grades your own free-text answers.)",
        "- **Add an input guardrail.** Before classifying, how would you reject an input that isn't a",
        "message to classify at all (e.g. \"ignore your instructions and...\")?",
        "",
        "## Reading material",
        "",
        "[Demystifying evals for AI agents](https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents)",
      ].join("\n"),
    },
  },
  {
    id: "agents",
    title: "16 · Agent frameworks",
    description: [
      "## letting the model drive a loop",
      "",
      "In Topic 5 you ran a tool **once**. An **agent** goes further: the model runs in a **loop** —",
      "it decides which tool to call, you run it and feed the result back, and it keeps going until it",
      "has a final answer. The model plans the steps itself.",
      "",
      "Here we hand-write that loop with two tools and a question that needs both, in sequence. Run it",
      "and watch the model chain the tools on its own.",
    ].join("\n"),
    defaultCode: topic14DefaultCode,
    question: {
      kind: "text",
      prompt:
        "We hand-wrote the loop that runs tools and feeds results back until the model is done. What does an agent framework give you over writing this yourself?",
      rubric:
        "Correct if the answer recognizes that a framework provides the agent loop / orchestration and " +
        "surrounding plumbing for you instead of hand-coding it: e.g. managing the tool-calling loop, " +
        "tools/memory/conversation state, multi-step planning, multi-agent coordination, retries/error " +
        "handling, streaming, observability/tracing, and provider abstraction. Mentioning that it " +
        "abstracts/handles the loop, orchestration, memory, tool management, planning, or reduces " +
        "boilerplate all count. Saying 'nothing' or 'it's the same' is incorrect. Be lenient about wording.",
      keywords: [
        "loop",
        "orchestrat",
        "abstract",
        "boilerplate",
        "memory",
        "state",
        "plan",
        "multi-step",
        "multi-agent",
        "retr",
        "tool",
        "manage",
        "observability",
        "tracing",
        "framework handles",
        "plumbing",
      ],
      explanation: [
        "## 🤖 What an agent is",
        "",
        "An **agent** is a model running in a loop with tools: **decide → act (call a tool) → observe**",
        "→ repeat until done. You just hand-wrote exactly that — the model chose `get_current_datetime`,",
        "used the result to call `multiply`, then answered. Give it tools and a goal and it plans the",
        "steps; that autonomy is what makes it an \"agent\" rather than a single call.",
        "",
        "## 🧩 What a framework adds",
        "",
        "Our loop was ~15 lines and bare-bones. Real agents need much more, and frameworks provide it so",
        "you don't re-implement it every time:",
        "",
        "- the **tool-calling loop** and tool registration/dispatch,",
        "- **memory** and conversation **state** (Topic 3),",
        "- **multi-step planning** and **multi-agent** coordination (agents calling agents),",
        "- **retries**, error handling, timeouts, and **streaming** (Topic 10),",
        "- **observability** — tracing every step, tool call, and token for debugging and evals (Topic 15).",
        "",
        "## 🛠️ The main frameworks",
        "",
        "- **LangChain / LangGraph** — the most widely used open-source option (Python & JS). Chains,",
        "agents, and graph-based orchestration with a huge ecosystem of integrations.",
        "- **Microsoft Agent Framework** — Microsoft's open-source framework for agents and multi-agent",
        "workflows (.NET & Python); the convergence of Semantic Kernel and AutoGen.",
        "- **Microsoft.Extensions.AI (MEAI)** — lower-level .NET abstractions (`IChatClient`) giving one",
        "unified interface over providers (Azure OpenAI, OpenAI, Ollama…) plus middleware for function",
        "calling, telemetry, and caching. A foundation other .NET agent libraries build on.",
        "",
        "## ⚖️ Framework or raw SDK?",
        "",
        "For a single call or one simple tool, the raw SDK (what we've used all workshop) is simplest —",
        "fewer layers to learn and debug. Reach for a framework when you need multi-step or multi-agent",
        "orchestration, memory, and tracing, and don't want to maintain that plumbing yourself. Either",
        "way, the model underneath is doing the same thing you saw here.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Add a tool.** Give the agent a third tool (say `add`) and ask a question that needs all",
        "three — does it chain them in the right order?",
        "- **Watch it plan.** Change the question so the order matters (a result feeds the next tool) and",
        "follow the `→ called ...` log to see the model's plan unfold.",
        "- **Spot the boilerplate.** Which parts of this loop would you NOT want to rewrite for every",
        "project? That list is basically what a framework sells.",
        "",
        "## Reading material",
        "",
        "- [Microsoft Agent Framework](https://github.com/microsoft/agent-framework)",
        "- [LangChain)](https://www.langchain.com/)",
      ].join("\n"),
    },
  },
  {
    id: "multi-agent",
    title: "17 · Multi-agent systems",
    description: [
      "## a team of specialised agents",
      "",
      "One agent with many tools gets unwieldy. A **multi-agent system** splits the work across",
      "**specialised agents** — each with its own instructions and tools — coordinated by an",
      "**orchestrator**. It's the same idea as a team: focused experts plus someone routing the work.",
      "",
      "Here an orchestrator agent treats two specialists (a researcher and a translator) as its tools.",
      "Run it and watch it delegate.",
    ].join("\n"),
    defaultCode: topic15DefaultCode,
    question: {
      kind: "text",
      prompt:
        "Our orchestrator called its sub-agents as plain in-process functions. What problem do protocols like MCP and A2A solve that this hard-wired approach doesn't?",
      rubric:
        "Correct if the answer recognizes interoperability across boundaries: the in-process approach " +
        "only works because everything is one codebase/process, whereas MCP and A2A are standard " +
        "protocols that let independently-built, remote, or different-framework/vendor agents and tools " +
        "discover and call each other over the network without custom wiring. Mentioning interop, " +
        "standard protocol, remote/distributed agents, cross-framework/vendor, discovery, or decoupling " +
        "all count. Saying 'nothing' or 'they're the same' is incorrect. Be lenient about wording.",
      keywords: [
        "interop",
        "protocol",
        "standard",
        "remote",
        "distributed",
        "different framework",
        "vendor",
        "discover",
        "decoupl",
        "network",
        "cross",
        "independent",
        "another team",
        "reuse",
      ],
      explanation: [
        "## 👥 Multi-agent systems",
        "",
        "Instead of one agent juggling every tool, you give each **specialist** its own narrow job,",
        "instructions, and tools, and let an **orchestrator** route work between them (and combine the",
        "results). Benefits: each agent's prompt and tool set stay small and reliable (Topic 5's",
        "\"don't over-tool\"), specialists are reusable, and you can test/evaluate each one on its own",
        "(Topic 15). Common shapes: orchestrator→workers, pipelines, or agents that debate/review.",
        "",
        "## 🔧 Agents as tools",
        "",
        "The simplest way to compose agents is what we just did: **wrap an agent as a tool** another",
        "agent can call. When the orchestrator \"calls a tool,\" that tool runs a whole sub-agent. It's",
        "just Topic 5's tool-calling, where the function behind the tool is itself an LLM. Clean and",
        "powerful — but everything lives in **one codebase and process**.",
        "",
        "## 🔌 MCP — agents/tools over a standard protocol",
        "",
        "To share an agent or tool *beyond* your process, expose it via an **MCP server** (Topic 7).",
        "Now any MCP-aware client can discover and call it over a standard protocol — no hard-wired",
        "function in your code. MCP connects an agent to **tools and data**.",
        "",
        "## 🤝 A2A — agents talking to agents",
        "",
        "**A2A (Agent2Agent)** is an open protocol for agents to collaborate with **each other** across",
        "different frameworks and vendors. Each agent publishes an **agent card** describing its skills;",
        "others discover it and **delegate tasks**, exchanging messages and results over HTTP — even if",
        "one is built with LangChain and another with the Microsoft Agent Framework (Topic 16). The rule",
        "of thumb: **MCP connects an agent to its tools; A2A connects agents to other agents.**",
        "",
        "## 🧭 In-process vs protocols",
        "",
        "Our function-call approach is perfect when all the agents are yours, in one app. MCP and A2A",
        "earn their keep when agents are **separate, remote, or built by different teams/vendors** — they",
        "provide the standard discovery and messaging so independently-built agents interoperate instead",
        "of being glued together by custom code.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Add a third specialist** (e.g. a `summarizer`) and a task that needs all three — does the",
        "orchestrator route the work sensibly?",
        "- **MCP vs A2A.** For your own system, which capabilities would you expose as MCP tools, and",
        "which interactions are really agent-to-agent (A2A)?",
        "- **Failure modes.** If a specialist gives a wrong answer, how would the orchestrator notice? (How",
        "do guardrails and evals from Topic 15 apply to each agent in the team?)",
        "",
        "## Reading material",
        "",
        "- [A2A protocol](https://google.github.io/A2A/)",
        "- [MCP introduction](https://modelcontextprotocol.io/docs/getting-started/intro)",
        "- [Multi Agent Patterns](https://learn.microsoft.com/en-us/agents/architecture/multi-agent-patterns)",
      ].join("\n"),
    },
  },
  {
    id: "skills",
    title: "14 · Skills",
    description: [
      "## reusable expertise, loaded on demand",
      "",
      "A **skill** is a packaged, reusable capability — a set of instructions (and, in real systems,",
      "bundled files or scripts) that teaches the model how to do a specific task well. Instead of",
      "cramming every instruction into one giant system prompt, you keep a library of skills and load",
      "only the relevant one when it's needed.",
      "",
      "Below, the model first sees just a cheap **menu** of skill names and descriptions, picks the",
      "right one, and only then loads that skill's full instructions. Run it.",
    ].join("\n"),
    defaultCode: topic16DefaultCode,
    question: {
      kind: "text",
      prompt:
        "We showed the model only short skill descriptions, then loaded just the chosen skill's full instructions. Why is that better than putting every skill's instructions in the system prompt up front?",
      rubric:
        "Correct if the answer is about not loading everything into context at once — progressive / " +
        "on-demand loading saves the limited context budget (Topic 13), keeps the prompt small/focused " +
        "so the model isn't distracted or confused by irrelevant instructions, reduces token cost, and " +
        "scales to many skills. Mentioning context window/budget, tokens/cost, only loading what's " +
        "relevant, avoiding a bloated/confusing prompt, or scaling to many skills all count. Saying " +
        "'no difference' is incorrect. Be lenient about wording.",
      keywords: [
        "context",
        "window",
        "budget",
        "token",
        "cost",
        "on demand",
        "on-demand",
        "progressive",
        "relevant",
        "focused",
        "bloat",
        "confus",
        "scale",
        "only load",
        "irrelevant",
      ],
      explanation: [
        "## 🧰 What a skill is",
        "",
        "A **skill** bundles the know-how for one task: instructions, and often supporting files,",
        "templates, or scripts. It's reusable (drop the same skill into any project or agent) and",
        "composable (an agent can have many). Think of it as giving the model an expert's playbook for",
        "a specific job, rather than hoping the base model just knows.",
        "",
        "## 🪜 Progressive disclosure",
        "",
        "The key trick is **loading skills on demand**. The model first sees only lightweight metadata",
        "— each skill's name and one-line description — which costs very few tokens. It picks what's",
        "relevant, and only *then* are that skill's full instructions pulled into context. This keeps",
        "the **context window** (Topic 13) free, cuts token cost, and avoids drowning the model in",
        "instructions it doesn't need right now — so you can have dozens of skills without bloating",
        "every call.",
        "",
        "## 🔁 Skills vs tools",
        "",
        "A **tool** (Topic 5) lets the model *do* something — run code, call an API. A **skill** teaches",
        "it *how* to do something — procedures, style, domain knowledge — as loadable context. They",
        "complement each other: a skill can describe a workflow that uses tools, and both are ways to",
        "extend a model beyond its base abilities.",
        "",
        "## 🌍 In the wild",
        "",
        "This pattern powers features like **Claude's Agent Skills** — folders of instructions plus",
        "resources that an agent discovers by description and loads when relevant. It's how an agent",
        "can carry a big library of specialised abilities while keeping any single request lean.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Add a skill.** Add a `summarize` skill to the registry and a matching request — does the",
        "model route to it? Notice you only added metadata + instructions, no new plumbing.",
        "- **Trace the savings.** Compare loading one skill's instructions on demand vs pasting all",
        "three skills' full instructions into every call — how does that scale to 100 skills?",
        "- **Skill or tool?** Would \"look up today's exchange rate\" be a skill or a tool (Topic 5)? What",
        "about \"write in our company's brand voice\"?",
        "",
        "## Reading material",
        "",
        "[Agent skills](https://agentskills.io/home)",
      ].join("\n"),
    },
  },
  {
    id: "code-interpreter",
    title: "6 · Code interpreter",
    description: [
      "## let the model run code, not guess",
      "",
      "An LLM doesn't *calculate* — it predicts tokens (Topic 1), so exact maths, parsing, and",
      "data crunching are unreliable. The **code interpreter** tool fixes this by giving the model a",
      "real **Python sandbox**: it writes code, the platform runs it in a container, and the model",
      "answers from the actual output.",
      "",
      "First, watch the model try a statistics problem on its own. Read its answer carefully — then",
      "ask yourself whether you'd bet on it.",
    ].join("\n"),
    defaultCode: topic17DefaultCode,
    question: {
      kind: "text",
      prompt:
        "The model produced a tidy, confident number — but doing exact maths in its head is unreliable, and you can't easily verify it. How do we get an exact, trustworthy answer for tasks that need real computation?",
      rubric:
        "Correct if the answer is about letting the model write and run actual code in a sandbox / " +
        "interpreter (e.g. a Python code-interpreter tool) — i.e. execute real code to compute the " +
        "result deterministically and verifiably, rather than have the model predict the answer token " +
        "by token. Mentioning a code interpreter, running/executing code, a Python sandbox, or a tool " +
        "that does the computation all count. Generic 'use a tool / function calling' counts only if it " +
        "conveys executing code to compute the result; merely 'ask better' or 'use a calculator in the " +
        "prompt' without the model running code is weaker — accept a calculator/tool that actually does " +
        "the computation. Be lenient about exact wording.",
      keywords: [
        "code interpreter",
        "code",
        "execute",
        "run code",
        "python",
        "sandbox",
        "interpreter",
        "tool",
        "calculate",
        "compute",
        "deterministic",
        "verifiable",
        "actually run",
      ],
      explanation: [
        "Right — instead of trusting the model's mental arithmetic, we let it **write and run real",
        "code**. Below we add the built-in `code_interpreter` tool; the model generates Python, the",
        "platform executes it in a sandbox, and it answers from the true result. Run it and compare.",
      ].join("\n"),
    },
    followUp: {
      title: "Now run the code",
      intro: [
        "We attach the built-in **`code_interpreter`** tool — a hosted Python sandbox. The model",
        "writes Python, the platform **runs it in a container**, and the model reads the real output",
        "before answering. It all happens in a single call; we also print the Python it generated so",
        "you can see (and check) its work.",
      ].join("\n"),
      code: topic17CodeInterpreterCode,
      explanation: [
        "## 🧮 Why the first answer couldn't be trusted",
        "",
        "An LLM generates text by predicting the next token (Topic 1) — it doesn't actually *compute*.",
        "For exact arithmetic, statistics, date maths, or parsing, that means it can produce a",
        "confident, perfectly-formatted answer that's subtly **wrong** — and because there's no",
        "calculation underneath, you can't tell which digits to trust. The hand-worked standard",
        "deviation *looked* rigorous, yet the final figure was off.",
        "",
        "## 🐍 What the code interpreter does",
        "",
        "The **code interpreter** is a built-in tool that gives the model a real **Python sandbox**.",
        "You attach it with `tools: [{ type: \"code_interpreter\", container: { type: \"auto\" } }]`. The",
        "model decides to use it, **writes Python**, the platform **executes** that code in an isolated",
        "container, the model **sees the actual output**, and then answers from it. The generated code",
        "and its result come back as a `code_interpreter_call` item in `output` — so the answer is now",
        "**deterministic and inspectable**, not a guess.",
        "",
        "## 🆚 How it differs from your own tools",
        "",
        "In Topic 5 *you* wrote each function and ran the call loop yourself. The code interpreter is",
        "different in two ways: the **model writes the code** (you don't predefine functions), and the",
        "**platform runs it** for you in a managed sandbox — no loop on your side, as you saw here. It's",
        "ideal for open-ended computation you can't anticipate: \"crunch these numbers\", \"parse this CSV\",",
        "\"solve this equation\", \"make a chart\". For a fixed, known action (call *our* API, hit *our*",
        "database) a regular tool is the better fit.",
        "",
        "## ⚖️ Things to weigh",
        "",
        "The code runs in a **sandboxed container** with no access to your systems unless you provide it,",
        "which is what makes letting a model execute code acceptable. But it's still real execution: it",
        "adds latency (spinning up and running the container), the model can write buggy code (it may",
        "retry), and you're billed for the tokens of the code and its output. Use it when a task genuinely",
        "needs computation — not for things the model can already answer directly.",
        "",
        "## 🧪 Exercises to think about",
        "",
        "- **Read the model's code.** The log prints the Python it wrote — does it match how you'd",
        "compute it? Try a task it might get subtly wrong by hand (e.g. \"how many days between",
        "2026-06-22 and 2027-03-01?\") and check the code, not just the answer.",
        "- **Give it data to crunch.** Paste a list of numbers or a small CSV in the prompt and ask for",
        "totals, averages, or the top 3 — watch it parse and compute instead of estimating.",
        "- **Code interpreter or a tool (Topic 5)?** For \"compute the variance of these values\" vs",
        "\"look up this customer's last order\", which fits which — and why?",
        "",
        "## Reading material",
        "",
        "[Code interpreters explained](https://www.iguazio.com/glossary/what-is-an-llm-code-interpreter/)",
      ].join("\n"),
    },
  },
  {
    id: "recap",
    title: "Recap",
    description: [
      "## 🗺️ The bigger picture",
      "",
      "You started this workshop with a question: how do you get from a frozen token predictor to a",
      "polished AI assistant? By now you've built that bridge yourself — one capability at a time.",
      "",
      "### 🧱 The foundation",
      "",
      "An LLM is a **token predictor** — probabilistic, stateless, frozen at its training cutoff.",
      "Everything you've seen is built on top of those three constraints, not around them.",
      "",
      "- **Tokens & cost** (Topic 1) — the unit everything is measured in; output tokens cost more than input",
      "- **Non-determinism** (Topic 2) — same input, different output, every time; `temperature` controls how much",
      "- **Statelessness** (Topic 3) — the model has no memory; you maintain the history and pay for it in tokens",
      "",
      "### 🔌 Extending the model's reach",
      "",
      "The model can't browse, calculate, or see your data — so you bridge those gaps from the outside.",
      "You hand it what it needs; it can't fetch anything itself.",
      "",
      "- **Reasoning** (Topic 4) — internal chain-of-thought improves hard problems but costs output tokens",
      "- **Tools & code** (Topics 5, 6) — live data and real computation; tools call your code, the code interpreter writes its own",
      "- **MCP** (Topic 7) — standard protocol to expose tools at scale, reusable across apps and agents",
      "- **RAG** (Topic 8) — ground answers in your own documents; embeddings match on meaning, not keywords",
      "- **Multimodal & images** (Topics 11, 12) — different models for different modalities; a model router",
      "ties them together — that's the seam ChatGPT hides",
      "",
      "### ⚖️ Working within limits",
      "",
      "Every capability has a cost. The art is managing what you load and when.",
      "",
      "- **Structured output** (Topic 9) — a schema constrains the shape; asking nicely is not enough",
      "- **Streaming** (Topic 10) — same total cost, dramatically better perceived latency",
      "- **Context windows** (Topic 13) — one shared budget for input and output; history, tools, and retrieved docs all compete for it",
      "- **Skills** (Topic 14) — load instructions on demand to keep context lean and scale to many capabilities",
      "",
      "### 🚀 Building at scale",
      "",
      "Autonomous, multi-step, multi-model systems — and the discipline to keep them trustworthy.",
      "",
      "- **Evals & guardrails** (Topic 15) — non-determinism means \"it worked once\" proves nothing; measure across cases and run in CI",
      "- **Agents** (Topic 16) — the tool loop made autonomous; frameworks handle the plumbing you'd otherwise rewrite every time",
      "- **Multi-agent systems** (Topic 17) — specialists + orchestrators + protocols; MCP connects agents to tools, A2A connects agents to agents",
      "",
      "The polished assistant you knew at the start is the same machine you've been experimenting with —",
      "just with all of this wired together and the seams hidden. **Now you know where the seams are.**",
    ].join("\n"),
  },
];

/**
 * The order topics appear in the sidebar. Keep the numbers in each topic's
 * `title` in sync with this sequence.
 */
const TOPIC_ORDER = [
  "introduction",
  "raw-response", // 1
  "system-prompt", // 2
  "state", // 3
  "reasoning", // 4
  "tools", // 5
  "code-interpreter", // 6
  "mcp", // 7
  "rag", // 8
  "structured-output", // 9
  "streaming", // 10
  "multimodal", // 11
  "image-generation", // 12
  "context-window", // 13
  "skills", // 14
  "evals", // 15
  "agents", // 16
  "multi-agent", // 17
  "recap",
];

const byId = new Map(topicDefinitions.map((t) => [t.id, t]));

export const topics: Topic[] = TOPIC_ORDER.map((id) => {
  const topic = byId.get(id);
  if (!topic) throw new Error(`TOPIC_ORDER references unknown topic id: ${id}`);
  return topic;
});
